import { Business } from "@/types/game";
import { createBusinessUpgrades } from "./businessUpgrades";

const createBusiness = (data: {
  id: string;
  name: string;
  icon: string;
  baseRevenue: number;
  baseCost: number;
  maxEmployees: number;
  category: 'financial' | 'food' | 'tech' | 'retail' | 'energy' | 'entertainment';
  imageUrl?: string;
}): Business => ({
  ...data,
  level: 0,
  owned: false,
  autoGenerate: false,
  revenuePerHour: 0,
  runningCostsPerHour: 0,
  netIncomePerHour: 0,
  purchasePrice: 0,
  totalInvested: 0,
  employees: 0,
  employeeSalaryPerHour: 0,
  maintenanceCostPerHour: 0,
  utilitiesCostPerHour: 0,
  marketingBudgetPerHour: 0,
  operatingHours: 24,
  marketingLevel: 0,
  efficiencyLevel: 0,
  qualityLevel: 0,
  automationLevel: 0,
  customerSatisfaction: 50,
  reputationScore: 50,
  upgrades: createBusinessUpgrades(data.id, data.baseRevenue, 1),
  totalProfit: 0,
  totalRevenue: 0,
});

const BUSINESSES_DATA: Business[] = [
  createBusiness({
    id: "lemonade_stand",
    name: "Lemonade Stand",
    icon: "🍋",
    baseRevenue: 30,
    baseCost: 100,
    maxEmployees: 1,
    category: 'food',
    imageUrl: "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f2d?w=800",
  }),
  createBusiness({
    id: "atm",
    name: "ATM Machine",
    icon: "🏧",
    baseRevenue: 140,
    baseCost: 5000,
    maxEmployees: 0,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/97d366c1-ae78-4e4c-bcd6-f8233f15f96d.png",
  }),
  createBusiness({
    id: "coffee_cart",
    name: "Coffee Cart",
    icon: "☕",
    baseRevenue: 250,
    baseCost: 8000,
    maxEmployees: 2,
    category: 'food',
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
  }),
  createBusiness({
    id: "food_truck",
    name: "Food Truck",
    icon: "🚚",
    baseRevenue: 750,
    baseCost: 25000,
    maxEmployees: 3,
    category: 'food',
    imageUrl: "https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=800",
  }),
  createBusiness({
    id: "vending_machines",
    name: "Vending Machine Route",
    icon: "🏪",
    baseRevenue: 500,
    baseCost: 15000,
    maxEmployees: 1,
    category: 'retail',
    imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800",
  }),
  createBusiness({
    id: "credit_union",
    name: "Credit Union",
    icon: "💳",
    baseRevenue: 1800,
    baseCost: 50000,
    maxEmployees: 5,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/1539452e-cca1-40ad-8204-61ee00597e0e.png",
  }),
  createBusiness({
    id: "burger_joint",
    name: "Burger Joint",
    icon: "🍔",
    baseRevenue: 2500,
    baseCost: 75000,
    maxEmployees: 6,
    category: 'food',
  }),
  createBusiness({
    id: "convenience_store",
    name: "Convenience Store",
    icon: "🏪",
    baseRevenue: 3200,
    baseCost: 100000,
    maxEmployees: 4,
    category: 'retail',
  }),
  createBusiness({
    id: "car_wash",
    name: "Car Wash",
    icon: "🚗",
    baseRevenue: 4000,
    baseCost: 120000,
    maxEmployees: 5,
    category: 'retail',
  }),
  createBusiness({
    id: "tech_startup",
    name: "Tech Startup",
    icon: "💻",
    baseRevenue: 6500,
    baseCost: 200000,
    maxEmployees: 10,
    category: 'tech',
  }),
  createBusiness({
    id: "boutique_shop",
    name: "Boutique Shop",
    icon: "👗",
    baseRevenue: 5500,
    baseCost: 180000,
    maxEmployees: 5,
    category: 'retail',
  }),
  createBusiness({
    id: "pizza_restaurant",
    name: "Pizza Restaurant",
    icon: "🍕",
    baseRevenue: 7000,
    baseCost: 250000,
    maxEmployees: 8,
    category: 'food',
  }),
  createBusiness({
    id: "gym",
    name: "Fitness Gym",
    icon: "🏋️",
    baseRevenue: 9000,
    baseCost: 300000,
    maxEmployees: 7,
    category: 'entertainment',
  }),
  createBusiness({
    id: "loan_office",
    name: "Loan Office",
    icon: "💰",
    baseRevenue: 15000,
    baseCost: 500000,
    maxEmployees: 8,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/ff814405-7eef-4d07-8406-780c0f192340.png",
  }),
  createBusiness({
    id: "sushi_bar",
    name: "Sushi Bar",
    icon: "🍣",
    baseRevenue: 18000,
    baseCost: 600000,
    maxEmployees: 7,
    category: 'food',
  }),
  createBusiness({
    id: "mobile_app",
    name: "Mobile App Dev",
    icon: "📱",
    baseRevenue: 22000,
    baseCost: 750000,
    maxEmployees: 12,
    category: 'tech',
  }),
  createBusiness({
    id: "fashion_store",
    name: "Fashion Store",
    icon: "👔",
    baseRevenue: 28000,
    baseCost: 900000,
    maxEmployees: 8,
    category: 'retail',
  }),
  createBusiness({
    id: "arcade",
    name: "Arcade",
    icon: "🎮",
    baseRevenue: 32000,
    baseCost: 1000000,
    maxEmployees: 6,
    category: 'entertainment',
  }),
  createBusiness({
    id: "pharmacy",
    name: "Pharmacy",
    icon: "💊",
    baseRevenue: 42000,
    baseCost: 1400000,
    maxEmployees: 10,
    category: 'retail',
  }),
  createBusiness({
    id: "steakhouse",
    name: "Steakhouse",
    icon: "🥩",
    baseRevenue: 50000,
    baseCost: 1750000,
    maxEmployees: 15,
    category: 'food',
  }),
  createBusiness({
    id: "accounting_firm",
    name: "Accounting Firm",
    icon: "📊",
    baseRevenue: 65000,
    baseCost: 2200000,
    maxEmployees: 15,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/cd5fc891-e289-4479-9563-3cece0397cc7.png",
  }),
  createBusiness({
    id: "saas_company",
    name: "SaaS Company",
    icon: "☁️",
    baseRevenue: 85000,
    baseCost: 3000000,
    maxEmployees: 20,
    category: 'tech',
  }),
  createBusiness({
    id: "electronics_store",
    name: "Electronics Store",
    icon: "📺",
    baseRevenue: 95000,
    baseCost: 3500000,
    maxEmployees: 12,
    category: 'retail',
  }),
  createBusiness({
    id: "solar_farm",
    name: "Solar Farm",
    icon: "☀️",
    baseRevenue: 110000,
    baseCost: 4000000,
    maxEmployees: 10,
    category: 'energy',
  }),
  createBusiness({
    id: "fine_dining",
    name: "Fine Dining Restaurant",
    icon: "🍽️",
    baseRevenue: 135000,
    baseCost: 5000000,
    maxEmployees: 25,
    category: 'food',
  }),
  createBusiness({
    id: "movie_theater",
    name: "Movie Theater",
    icon: "🎬",
    baseRevenue: 180000,
    baseCost: 6500000,
    maxEmployees: 20,
    category: 'entertainment',
  }),
  createBusiness({
    id: "data_center",
    name: "Data Center",
    icon: "🖥️",
    baseRevenue: 220000,
    baseCost: 8000000,
    maxEmployees: 15,
    category: 'tech',
  }),
  createBusiness({
    id: "forex_broker",
    name: "Forex Brokerage",
    icon: "💱",
    baseRevenue: 280000,
    baseCost: 10000000,
    maxEmployees: 25,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/f4775fef-1231-4913-8031-cb4ddc33e96d.png",
  }),
  createBusiness({
    id: "ai_company",
    name: "AI Research Company",
    icon: "🤖",
    baseRevenue: 350000,
    baseCost: 12500000,
    maxEmployees: 30,
    category: 'tech',
  }),
  createBusiness({
    id: "department_store",
    name: "Department Store",
    icon: "🏬",
    baseRevenue: 420000,
    baseCost: 15000000,
    maxEmployees: 40,
    category: 'retail',
  }),
  createBusiness({
    id: "wind_farm",
    name: "Wind Farm",
    icon: "💨",
    baseRevenue: 550000,
    baseCost: 20000000,
    maxEmployees: 15,
    category: 'energy',
  }),
  createBusiness({
    id: "michelin_restaurant",
    name: "Michelin Star Restaurant",
    icon: "⭐",
    baseRevenue: 700000,
    baseCost: 25000000,
    maxEmployees: 35,
    category: 'food',
  }),
  createBusiness({
    id: "theme_park",
    name: "Theme Park",
    icon: "🎢",
    baseRevenue: 1100000,
    baseCost: 40000000,
    maxEmployees: 100,
    category: 'entertainment',
  }),
  createBusiness({
    id: "investment_bank",
    name: "Investment Bank",
    icon: "🏦",
    baseRevenue: 1500000,
    baseCost: 55000000,
    maxEmployees: 50,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/54efba0f-5ac1-486f-bffb-ba3011618a42.png",
  }),
  createBusiness({
    id: "gaming_studio",
    name: "Gaming Studio",
    icon: "🎯",
    baseRevenue: 1850000,
    baseCost: 70000000,
    maxEmployees: 45,
    category: 'tech',
  }),
  createBusiness({
    id: "luxury_mall",
    name: "Luxury Shopping Mall",
    icon: "💎",
    baseRevenue: 2500000,
    baseCost: 95000000,
    maxEmployees: 80,
    category: 'retail',
  }),
  createBusiness({
    id: "nuclear_plant",
    name: "Nuclear Power Plant",
    icon: "⚛️",
    baseRevenue: 3500000,
    baseCost: 130000000,
    maxEmployees: 200,
    category: 'energy',
  }),
  createBusiness({
    id: "restaurant_chain",
    name: "Restaurant Chain",
    icon: "🍴",
    baseRevenue: 5200000,
    baseCost: 200000000,
    maxEmployees: 200,
    category: 'food',
  }),
  createBusiness({
    id: "hedge_fund",
    name: "Hedge Fund",
    icon: "📈",
    baseRevenue: 7500000,
    baseCost: 280000000,
    maxEmployees: 40,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/196a61db-e741-4239-9fc3-d40ad7b6135e.png",
  }),
  createBusiness({
    id: "social_network",
    name: "Social Network",
    icon: "📲",
    baseRevenue: 11000000,
    baseCost: 400000000,
    maxEmployees: 100,
    category: 'tech',
  }),
  createBusiness({
    id: "ecommerce_giant",
    name: "E-Commerce Giant",
    icon: "🛒",
    baseRevenue: 17500000,
    baseCost: 650000000,
    maxEmployees: 500,
    category: 'retail',
  }),
  createBusiness({
    id: "streaming_service",
    name: "Streaming Service",
    icon: "📺",
    baseRevenue: 22000000,
    baseCost: 850000000,
    maxEmployees: 80,
    category: 'entertainment',
  }),
  createBusiness({
    id: "private_equity",
    name: "Private Equity Firm",
    icon: "💼",
    baseRevenue: 35000000,
    baseCost: 1400000000,
    maxEmployees: 35,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/11eabb34-092d-4949-8a04-d42615bbab55.png",
  }),
  createBusiness({
    id: "cloud_provider",
    name: "Cloud Provider",
    icon: "☁️",
    baseRevenue: 70000000,
    baseCost: 2700000000,
    maxEmployees: 300,
    category: 'tech',
  }),
  createBusiness({
    id: "global_retailer",
    name: "Global Retail Chain",
    icon: "🌍",
    baseRevenue: 105000000,
    baseCost: 4000000000,
    maxEmployees: 2000,
    category: 'retail',
  }),
  createBusiness({
    id: "fusion_reactor",
    name: "Fusion Reactor",
    icon: "⚡",
    baseRevenue: 175000000,
    baseCost: 6500000000,
    maxEmployees: 150,
    category: 'energy',
  }),
  createBusiness({
    id: "venture_capital",
    name: "Venture Capital",
    icon: "🚀",
    baseRevenue: 280000000,
    baseCost: 11000000000,
    maxEmployees: 30,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/3886570a-2b30-41af-9688-b037a692ddc4.png",
  }),
  createBusiness({
    id: "space_tourism",
    name: "Space Tourism Company",
    icon: "🛸",
    baseRevenue: 525000000,
    baseCost: 20000000000,
    maxEmployees: 200,
    category: 'entertainment',
  }),
  createBusiness({
    id: "crypto_exchange",
    name: "Crypto Exchange",
    icon: "₿",
    baseRevenue: 1050000000,
    baseCost: 40000000000,
    maxEmployees: 100,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/e81cc3b5-e905-4906-b8ac-53d3a244b4a4.png",
  }),
  createBusiness({
    id: "quantum_computing",
    name: "Quantum Computing Corp",
    icon: "⚛️",
    baseRevenue: 2100000000,
    baseCost: 80000000000,
    maxEmployees: 250,
    category: 'tech',
  }),
  createBusiness({
    id: "central_bank",
    name: "Central Bank",
    icon: "🏛️",
    baseRevenue: 7000000000,
    baseCost: 270000000000,
    maxEmployees: 200,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/478c720b-f9a2-4f3c-9b26-e805a0197480.png",
  }),
  createBusiness({
    id: "imf",
    name: "International Fund",
    icon: "🌍",
    baseRevenue: 35000000000,
    baseCost: 1350000000000,
    maxEmployees: 500,
    category: 'financial',
    imageUrl: "https://r2-pub.rork.com/generated-images/6e3966be-b4d0-4e9d-b17a-1114b29fe1d0.png",
  }),
];

export const INITIAL_BUSINESSES: Business[] = BUSINESSES_DATA.sort((a, b) => a.baseCost - b.baseCost);

export const AUTO_GENERATE_LEVEL = 1;
export const COST_MULTIPLIER = 1.15;
export const REVENUE_MULTIPLIER = 1.18;

export const EMPLOYEE_SALARY_PERCENTAGE = 0.15;
export const MAINTENANCE_COST_PERCENTAGE = 0.05;
export const UTILITIES_COST_PERCENTAGE = 0.03;
export const MARKETING_COST_PERCENTAGE = 0.02;

export const BASE_PROFIT_MARGIN = 0.45;

export const SECONDS_PER_HOUR = 3600;
