import { Property, PropertyCustomization } from "@/types/game";

const createPropertyCustomizations = (baseCost: number): PropertyCustomization[] => [
  {
    id: 'smart_home',
    name: 'Smart Home System',
    description: 'Automated climate, lighting, and security controls',
    cost: baseCost * 0.15,
    maintenanceReduction: 0.15,
    incomeBoost: 0.08,
    valueBoost: 0.12,
    unlocked: false,
    category: 'tech',
  },
  {
    id: 'solar_panels',
    name: 'Solar Panel Installation',
    description: 'Renewable energy system reducing utility costs',
    cost: baseCost * 0.2,
    maintenanceReduction: 0.25,
    incomeBoost: 0.12,
    valueBoost: 0.18,
    unlocked: false,
    category: 'eco',
  },
  {
    id: 'security_system',
    name: 'Advanced Security System',
    description: 'Comprehensive surveillance and alarm system',
    cost: baseCost * 0.1,
    insuranceReduction: 0.3,
    incomeBoost: 0.05,
    valueBoost: 0.08,
    unlocked: false,
    category: 'security',
  },
  {
    id: 'luxury_interior',
    name: 'Luxury Interior Upgrade',
    description: 'Premium finishes, appliances, and fixtures',
    cost: baseCost * 0.25,
    incomeBoost: 0.25,
    valueBoost: 0.3,
    unlocked: false,
    category: 'luxury',
  },
  {
    id: 'energy_efficient',
    name: 'Energy Efficiency Package',
    description: 'Insulation, windows, and HVAC upgrades',
    cost: baseCost * 0.18,
    maintenanceReduction: 0.2,
    taxReduction: 0.15,
    valueBoost: 0.15,
    unlocked: false,
    category: 'eco',
  },
  {
    id: 'roof_upgrade',
    name: 'Premium Roof System',
    description: 'Long-lasting roofing with weatherproofing',
    cost: baseCost * 0.12,
    maintenanceReduction: 0.3,
    valueBoost: 0.1,
    unlocked: false,
    category: 'efficiency',
  },
  {
    id: 'hvac_upgrade',
    name: 'High-Efficiency HVAC',
    description: 'Modern heating and cooling system',
    cost: baseCost * 0.14,
    maintenanceReduction: 0.18,
    incomeBoost: 0.07,
    valueBoost: 0.12,
    unlocked: false,
    category: 'efficiency',
  },
  {
    id: 'landscaping',
    name: 'Professional Landscaping',
    description: 'Beautiful outdoor spaces and gardens',
    cost: baseCost * 0.08,
    incomeBoost: 0.1,
    valueBoost: 0.15,
    unlocked: false,
    category: 'luxury',
  },
  {
    id: 'water_system',
    name: 'Water Conservation System',
    description: 'Efficient plumbing and water reclamation',
    cost: baseCost * 0.1,
    maintenanceReduction: 0.12,
    taxReduction: 0.1,
    valueBoost: 0.08,
    unlocked: false,
    category: 'eco',
  },
  {
    id: 'smart_access',
    name: 'Smart Access Control',
    description: 'Keyless entry and visitor management',
    cost: baseCost * 0.06,
    insuranceReduction: 0.15,
    incomeBoost: 0.05,
    valueBoost: 0.07,
    unlocked: false,
    category: 'tech',
  },
  {
    id: 'backup_power',
    name: 'Backup Power System',
    description: 'Generator and battery backup',
    cost: baseCost * 0.16,
    maintenanceReduction: 0.08,
    insuranceReduction: 0.2,
    valueBoost: 0.14,
    unlocked: false,
    category: 'tech',
  },
  {
    id: 'fire_suppression',
    name: 'Fire Suppression System',
    description: 'Automatic sprinklers and fire detection',
    cost: baseCost * 0.11,
    insuranceReduction: 0.35,
    valueBoost: 0.1,
    unlocked: false,
    category: 'security',
  },
];

const generatePropertyData = (property: Omit<Property, 'purchasePrice' | 'currentMarketValue' | 'marketTrend' | 'maintenanceCostPerHour' | 'taxesPerMonth' | 'insurancePerMonth' | 'rented' | 'rentIncome' | 'customizations' | 'tenantQuality' | 'conditionScore' | 'energyEfficiency' | 'securityLevel' | 'amenitiesLevel'>): Property => ({
  ...property,
  purchasePrice: 0,
  currentMarketValue: property.baseCost,
  marketTrend: 0,
  maintenanceCostPerHour: (property.incomePerHour * 0.12),
  taxesPerMonth: property.baseCost * 0.0008,
  insurancePerMonth: property.baseCost * 0.0004,
  rented: false,
  rentIncome: property.incomePerHour * 0.9,
  customizations: createPropertyCustomizations(property.baseCost),
  tenantQuality: 50,
  conditionScore: 100,
  energyEfficiency: 50,
  securityLevel: 30,
  amenitiesLevel: 30,
});

export const INITIAL_PROPERTIES: Property[] = [
  generatePropertyData({
    id: "studio_apt",
    name: "Studio Apartment",
    icon: "🏠",
    baseValue: 50000,
    baseCost: 50000,
    incomePerHour: 3,
    level: 0,
    owned: false,
    category: 'residential',
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
  }),
  generatePropertyData({
    id: "condo",
    name: "Downtown Condo",
    icon: "🏢",
    baseValue: 150000,
    baseCost: 150000,
    incomePerHour: 12,
    level: 0,
    owned: false,
    category: 'residential',
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
  }),
  generatePropertyData({
    id: "coffee_shop",
    name: "Coffee Shop",
    icon: "☕",
    baseValue: 100000,
    baseCost: 100000,
    incomePerHour: 10,
    level: 0,
    owned: false,
    category: 'commercial',
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
  }),
  generatePropertyData({
    id: "townhouse",
    name: "Suburban Townhouse",
    icon: "🏘️",
    baseValue: 350000,
    baseCost: 350000,
    incomePerHour: 35,
    level: 0,
    owned: false,
    category: 'residential',
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
  }),
  generatePropertyData({
    id: "retail_store",
    name: "Retail Store",
    icon: "🏬",
    baseValue: 500000,
    baseCost: 500000,
    incomePerHour: 60,
    level: 0,
    owned: false,
    category: 'commercial',
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
  }),
  generatePropertyData({
    id: "office_space",
    name: "Office Space",
    icon: "🏢",
    baseValue: 800000,
    baseCost: 800000,
    incomePerHour: 100,
    level: 0,
    owned: false,
    category: 'commercial',
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
  }),
  generatePropertyData({
    id: "villa",
    name: "Luxury Villa",
    icon: "🏰",
    baseValue: 1500000,
    baseCost: 1500000,
    incomePerHour: 180,
    level: 0,
    owned: false,
    category: 'luxury',
    imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
  }),
  generatePropertyData({
    id: "shopping_mall",
    name: "Shopping Mall",
    icon: "🛍️",
    baseValue: 3000000,
    baseCost: 3000000,
    incomePerHour: 400,
    level: 0,
    owned: false,
    category: 'commercial',
    imageUrl: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=800&q=80",
  }),
  generatePropertyData({
    id: "penthouse",
    name: "Manhattan Penthouse",
    icon: "🌆",
    baseValue: 5000000,
    baseCost: 5000000,
    incomePerHour: 700,
    level: 0,
    owned: false,
    category: 'luxury',
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  }),
  generatePropertyData({
    id: "hotel",
    name: "Boutique Hotel",
    icon: "🏨",
    baseValue: 10000000,
    baseCost: 10000000,
    incomePerHour: 1500,
    level: 0,
    owned: false,
    category: 'commercial',
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
  }),
  generatePropertyData({
    id: "beach_resort",
    name: "Private Beach Resort",
    icon: "🏖️",
    baseValue: 25000000,
    baseCost: 25000000,
    incomePerHour: 4000,
    level: 0,
    owned: false,
    category: 'luxury',
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
  }),
  generatePropertyData({
    id: "skyscraper",
    name: "Corporate Skyscraper",
    icon: "🏙️",
    baseValue: 50000000,
    baseCost: 50000000,
    incomePerHour: 9000,
    level: 0,
    owned: false,
    category: 'commercial',
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
  }),
  generatePropertyData({
    id: "private_island",
    name: "Private Island",
    icon: "🏝️",
    baseValue: 100000000,
    baseCost: 100000000,
    incomePerHour: 20000,
    level: 0,
    owned: false,
    category: 'exotic',
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
  }),
  generatePropertyData({
    id: "casino",
    name: "Luxury Casino",
    icon: "🎰",
    baseValue: 200000000,
    baseCost: 200000000,
    incomePerHour: 50000,
    level: 0,
    owned: false,
    category: 'commercial',
    imageUrl: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80",
  }),
  generatePropertyData({
    id: "space_hotel",
    name: "Space Hotel",
    icon: "🛸",
    baseValue: 1000000000,
    baseCost: 1000000000,
    incomePerHour: 300000,
    level: 0,
    owned: false,
    category: 'exotic',
    imageUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
  }),
];

export const PROPERTY_COST_MULTIPLIER = 1.20;
export const PROPERTY_INCOME_MULTIPLIER = 1.18;
