import { Stock } from "@/types/game";

export const INITIAL_STOCKS: Stock[] = [
  {
    id: "tech_blue_chip",
    name: "TechCore Inc",
    symbol: "TECH",
    currentPrice: 25,
    basePrice: 25,
    volatility: 0.08,
    sharesOwned: 0,
    priceHistory: [25],
  },
  {
    id: "energy_stable",
    name: "PowerGen Energy",
    symbol: "PGEN",
    currentPrice: 40,
    basePrice: 40,
    volatility: 0.10,
    sharesOwned: 0,
    priceHistory: [40],
  },
  {
    id: "tech_growth",
    name: "SoftVision Corp",
    symbol: "SOFT",
    currentPrice: 60,
    basePrice: 60,
    volatility: 0.15,
    sharesOwned: 0,
    priceHistory: [60],
  },
  {
    id: "retail_giant",
    name: "MegaMart Global",
    symbol: "MEGA",
    currentPrice: 80,
    basePrice: 80,
    volatility: 0.12,
    sharesOwned: 0,
    priceHistory: [80],
  },
  {
    id: "pharma_bio",
    name: "BioPharma Global",
    symbol: "BIOP",
    currentPrice: 120,
    basePrice: 120,
    volatility: 0.20,
    sharesOwned: 0,
    priceHistory: [120],
  },
  {
    id: "green_energy",
    name: "Green Energy Solutions",
    symbol: "GREN",
    currentPrice: 150,
    basePrice: 150,
    volatility: 0.18,
    sharesOwned: 0,
    priceHistory: [150],
  },
  {
    id: "ai_robotics",
    name: "AI Robotics Ltd",
    symbol: "AIRO",
    currentPrice: 250,
    basePrice: 250,
    volatility: 0.25,
    sharesOwned: 0,
    priceHistory: [250],
  },
  {
    id: "crypto_tech",
    name: "CryptoTech Corp",
    symbol: "CRYP",
    currentPrice: 350,
    basePrice: 350,
    volatility: 0.35,
    sharesOwned: 0,
    priceHistory: [350],
  },
  {
    id: "fintech_innovate",
    name: "FinTech Innovations",
    symbol: "FINT",
    currentPrice: 500,
    basePrice: 500,
    volatility: 0.22,
    sharesOwned: 0,
    priceHistory: [500],
  },
  {
    id: "space_mining",
    name: "Space Mining Corp",
    symbol: "SPCE",
    currentPrice: 800,
    basePrice: 800,
    volatility: 0.40,
    sharesOwned: 0,
    priceHistory: [800],
  },
  {
    id: "quantum_comp",
    name: "Quantum Computing",
    symbol: "QNTM",
    currentPrice: 1200,
    basePrice: 1200,
    volatility: 0.45,
    sharesOwned: 0,
    priceHistory: [1200],
  },
  {
    id: "nano_tech",
    name: "NanoTech Industries",
    symbol: "NANO",
    currentPrice: 2000,
    basePrice: 2000,
    volatility: 0.50,
    sharesOwned: 0,
    priceHistory: [2000],
  },
  {
    id: "biotech_gene",
    name: "Gene Therapeutics",
    symbol: "GENE",
    currentPrice: 3500,
    basePrice: 3500,
    volatility: 0.55,
    sharesOwned: 0,
    priceHistory: [3500],
  },
  {
    id: "fusion_energy",
    name: "Fusion Energy Corp",
    symbol: "FUSN",
    currentPrice: 5000,
    basePrice: 5000,
    volatility: 0.60,
    sharesOwned: 0,
    priceHistory: [5000],
  },
  {
    id: "crypto_btc",
    name: "Bitcoin ETF",
    symbol: "BTCE",
    currentPrice: 8000,
    basePrice: 8000,
    volatility: 0.70,
    sharesOwned: 0,
    priceHistory: [8000],
  },
  {
    id: "crypto_eth",
    name: "Ethereum ETF",
    symbol: "ETHE",
    currentPrice: 5000,
    basePrice: 5000,
    volatility: 0.75,
    sharesOwned: 0,
    priceHistory: [5000],
  },
  {
    id: "defi_protocol",
    name: "DeFi Protocol Index",
    symbol: "DEFI",
    currentPrice: 3000,
    basePrice: 3000,
    volatility: 0.85,
    sharesOwned: 0,
    priceHistory: [3000],
  },
  {
    id: "metaverse_platform",
    name: "Metaverse Platforms",
    symbol: "META",
    currentPrice: 12000,
    basePrice: 12000,
    volatility: 0.65,
    sharesOwned: 0,
    priceHistory: [12000],
  },
  {
    id: "ai_superintelligence",
    name: "AI Superintelligence",
    symbol: "AISP",
    currentPrice: 20000,
    basePrice: 20000,
    volatility: 0.80,
    sharesOwned: 0,
    priceHistory: [20000],
  },
  {
    id: "moon_base",
    name: "Lunar Industries",
    symbol: "MOON",
    currentPrice: 50000,
    basePrice: 50000,
    volatility: 0.90,
    sharesOwned: 0,
    priceHistory: [50000],
  },
];

export const TRADING_UNLOCK_THRESHOLD = 250000;
